
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 06 17:01:13 MDT 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 29;
  public static final int Declare = 49;
  public static final int Begin = 52;
  public static final int End = 48;
  public static final int Coma = 42;
  public static final int Until = 14;
  public static final int Llave_c = 36;
  public static final int Double = 8;
  public static final int Op_booleano = 32;
  public static final int Llave_a = 35;
  public static final int OpenDoor = 23;
  public static final int Ventilate = 16;
  public static final int Admit = 17;
  public static final int Aritmetico = 27;
  public static final int Option = 15;
  public static final int Else = 12;
  public static final int Start = 39;
  public static final int Corchete_c = 38;
  public static final int Corchete_a = 37;
  public static final int DriverLights = 22;
  public static final int Device = 10;
  public static final int EmptyRoom = 18;
  public static final int Numero_Dec = 45;
  public static final int Dispense = 19;
  public static final int Int = 4;
  public static final int Cadena = 9;
  public static final int Float = 7;
  public static final int Parentesis_c = 34;
  public static final int Condition = 11;
  public static final int Atlas = 2;
  public static final int Parentesis_a = 33;
  public static final int P_coma = 40;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Logic = 6;
  public static final int Texto = 46;
  public static final int As = 50;
  public static final int Char = 5;
  public static final int Op_atribucion = 30;
  public static final int Do = 13;
  public static final int Case = 51;
  public static final int Op_logico = 28;
  public static final int Dos_puntos = 41;
  public static final int Identificador = 43;
  public static final int Caracter = 47;
  public static final int RegisterA = 24;
  public static final int DeviceControl = 21;
  public static final int Op_incremento = 31;
  public static final int Distance = 20;
  public static final int Numero = 44;
  public static final int Exit = 25;
  public static final int Igual = 26;
  public static final int Comillas = 3;
}

